#!/usr/bin/env python3
"""Writes .vitepress/theme/app/tokens.css from the app's theme sources, so the HTML app frames use the
app's own colors. Usage: scripts/app-tokens.py <path to pomelo/rust>"""
import re
import sys
from pathlib import Path

rust = Path(sys.argv[1] if len(sys.argv) > 1 else "../pomelo/rust")
ui_theme = (rust / "crates/ui/src/theme.rs").read_text()
editor_theme = (rust / "crates/editor/src/theme.rs").read_text()


def block(source, name):
    start = source.index(f"fn {name}()")
    depth, i = 0, source.index("{", start)
    for j in range(i, len(source)):
        depth += {"{": 1, "}": -1}.get(source[j], 0)
        if depth == 0:
            return source[i:j]
    raise ValueError(name)


def ui_colors(name):
    body = block(ui_theme, name)
    colors = {k.replace("_", "-"): v for k, v in re.findall(r'(\w+): h\("(#[0-9a-fA-F]+)"\)', body)}
    ansi = re.search(r"terminal_ansi: \[(.*?)\]", body, re.S)
    if ansi:
        for index, value in enumerate(re.findall(r'h\("(#[0-9a-fA-F]+)"\)', ansi.group(1))):
            colors[f"ansi-{index}"] = value
    return colors


def editor_colors(name):
    body = block(editor_theme, name)
    rgb = lambda r, g, b: "#%02x%02x%02x" % (int(r), int(g), int(b))
    colors = {
        "syntax-" + k.replace(".", "-"): rgb(*c)
        for k, *c in re.findall(r'put\("([\w.]+)", Color::rgb\((\d+), (\d+), (\d+)\)\)', body)
    }
    return colors


def css(selector, colors):
    lines = [f"  --pa-{k}: {v};" for k, v in sorted(colors.items())]
    return selector + " {\n" + "\n".join(lines) + "\n}\n"


header = "/* Generated by scripts/app-tokens.py from the app's theme; do not edit by hand. */\n"
dark = {**ui_colors("one_dark"), **editor_colors("one_dark")}
light = {**ui_colors("one_light"), **editor_colors("one_light")}
out = Path(__file__).resolve().parent.parent / ".vitepress/theme/app/tokens.css"
out.write_text(header + css(".pa, html.dark .pa", dark) + css("html:not(.dark) .pa", light))
print(f"wrote {out} ({len(dark)} tokens)")
