#!/usr/bin/env python3
"""Writes .vitepress/theme/app/icons.js from the app's icon set, so the HTML app frames draw the same
glyphs. Monochrome icons take currentColor; engine and file-type logos keep their colors.
Usage: scripts/app-icons.py <path to pomelo/rust>"""
import json
import re
import sys
from pathlib import Path

rust = Path(sys.argv[1] if len(sys.argv) > 1 else "../pomelo/rust")
root = rust / "crates/ui/assets/icons"
icons = {}
for path in sorted(root.glob("*.svg")):
    svg = path.read_text()
    # The app draws these as masks tinted by the caller, so any color in the file stands for "the tint".
    svg = re.sub(r'(stroke|fill)="(?!none)[^"]+"', r'\1="currentColor"', svg)
    icons[path.stem] = svg
# Engine logos are single-color marks; the app fills each with its brand color.
render = (rust / "crates/database_ui/src/render.rs").read_text()
brand = {name.lower(): color for name, color in re.findall(r'IconKind::Engine(\w+), "(#[0-9A-Fa-f]{6})"', render)}
brand["apachekafka"] = brand.pop("kafka", "#DCE0E5")
for path in sorted((root / "engines").glob("*.svg")):
    svg = path.read_text()
    icons["engine-" + path.stem] = svg.replace("<svg ", f'<svg fill="{brand.get(path.stem, "currentColor")}" ', 1)
for path in sorted((root / "material").glob("*.svg")):
    icons["file-" + path.stem] = path.read_text()
cleaned = {}
for name, svg in icons.items():
    svg = re.sub(r"<\?xml[^>]*>|<!--.*?-->", "", svg, flags=re.S).strip()
    if "viewBox" not in svg:
        size = re.search(r'width="(\d+)"[^>]*height="(\d+)"', svg) or re.search(r'height="(\d+)"[^>]*width="(\d+)"', svg)
        if size:
            svg = svg.replace("<svg ", f'<svg viewBox="0 0 {size.group(1)} {size.group(2)}" ', 1)
    svg = re.sub(r'\s(width|height)="[^"]*"', "", svg, count=2)
    cleaned[name] = svg
out = Path(__file__).resolve().parent.parent / ".vitepress/theme/app/icons.js"
out.write_text("// Generated by scripts/app-icons.py from the app's icon set; do not edit by hand.\nexport default "
               + json.dumps(cleaned, indent=0) + "\n")
print(f"wrote {out} ({len(cleaned)} icons)")
